appId = "co.bambinito.sacn-monitor"
productName = "sACN Monitor"
copyright = "Copyright © 2023 ${author}"
files = [ "electron/**/*", "node_modules/**/*" ]
[extraMetadata]
main = "electron/main.js"

[directories]
buildResources = "assets"

[mac]
target = "dmg"
category = "public.app-category.utilities"
artifactName = "${name}-${version}.${ext}"

[win]
target = "nsis"
artifactName = "${name}-Setup-${version}.${ext}"

[linux]
target = "AppImage"
artifactName = "${name}-${version}.${ext}"
