baseURL = 'https://sacn-monitor.bambinito.net/'
languageCode = 'en-us'
title = 'sACN Monitor'
publishDir = "../public"
disableKinds = ['taxonomy', 'term']
# staticDir = ['static', '../build']
[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'FAQ'
    pageRef = '/faq/'
    weight = 20
