// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUniverseData(arg1) {
  return window['go']['main']['App']['GetUniverseData'](arg1);
}

export function GetUniverses() {
  return window['go']['main']['App']['GetUniverses']();
}
