// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dmx} from '../models';

export function GetInterfaces():Promise<Array<dmx.Interface>>;

export function GetUniverseData(arg1:string):Promise<any>;

export function GetUniverses():Promise<Array<dmx.Universe>>;

export function SetInterface(arg1:dmx.Interface):Promise<void>;
