// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInterfaces() {
  return window['go']['main']['App']['GetInterfaces']();
}

export function GetUniverseData(arg1) {
  return window['go']['main']['App']['GetUniverseData'](arg1);
}

export function GetUniverses() {
  return window['go']['main']['App']['GetUniverses']();
}

export function JoinUniverse(arg1) {
  return window['go']['main']['App']['JoinUniverse'](arg1);
}

export function SetInterface(arg1) {
  return window['go']['main']['App']['SetInterface'](arg1);
}
