// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dmx} from '../models';

export function ClearUniverses():Promise<void>;

export function GetInterfaces():Promise<Array<dmx.Interface>>;

export function GetUniverse(arg1:string):Promise<dmx.Universe>;

export function GetUniverses():Promise<Array<dmx.Universe>>;

export function JoinUniverse(arg1:number):Promise<void>;

export function SetInterface(arg1:dmx.Interface):Promise<void>;
